### ISSUE TITLE
shuffle() causes errors on ObservableList

### ISSUE THREAD

**Issue by montyr75** [dam0vm3nt/polymer_autonotify#7]
Calling `shuffle()` on an ObservableList causes an exception:

```
Uncaught Unhandled exception:
The null object does not have a method 'removeReference'.

NoSuchMethodError: method not found: 'removeReference'
Receiver: null
Arguments: ["4", Instance of 'ListPropertyNotifier']
```

**Comment by dam0vm3nt** [comment]
Hi @montyr75 I'm having trouble trying to reproduce this error. I've created a test case using an `ObservableList` and binding elements, then calling `shuffle` but everything seams to work. Can you give me more hints?

**Comment by dam0vm3nt** [comment]
ok, I succeeded. Had to put more elements and repeat shuffle many time.

**Comment by montyr75** [comment]
That's strange. One call to shuffle() broke it for me every time. Glad you
figured it out, though. I will check it out as soon as I can.

**Comment by dam0vm3nt** [comment]
yeah, it was depending on the permutation caused by `shuffle`. The higher the list size the higher the chances it would trigger the problem. With tiny lists (2-4 elements) you will have to try some time. But anyway it should be fixed now. I have a unit test case that will do 1000 times a `shuffle` and now it works.
